services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    command: start-dev --import-realm

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  api:
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ml_service

  ml_service:
    build: ./ml_service
    volumes:
      - ./ml_service:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
  
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    image: mono-dashboard
    ports:
      - "3000:3000"
    environment:
      # Variables d'environnement pour le RUNTIME (côté serveur)
      - NODE_ENV=production
      - API_URL=${API_URL}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - CLIENT_ID=fastapi-backend
      - CLIENT_SECRET=my-secret
      - NEXT_PUBLIC_CLIENT_ID=fastapi-backend
    depends_on:
      - api
      - ml_service
      - keycloak
    env_file:
      - .env

volumes:
  db_data: